services:
  - type: web
    name: studymate
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FIREBASE_CREDENTIALS
        sync: false